### ISSUE TITLE
Hacktoberfest Project Ideas Repo

### ISSUE THREAD

**Issue by praveenscience** [hkaur008/List-Of-Active-Repositories#6]
Hey Hargun, just got my Hacktoberfest Project ideas repo crossing 100 Stars! 💪🏻

Would love to be featured:

- Name: Hacktoberfest Project Ideas
- URL: https://github.com/praveenscience/Hacktoberfest-Project-Ideas
- Remarks: Hacktoberfest
- Tech Stack: Documentation / Tech

**Comment by hkaur008** [comment]
Okay I added mutiple section for different kind of repositories 😊

**Comment by praveenscience** [comment]
Oh where? I couldn't find it. That's why I asked. 🔥

**Comment by hkaur008** [comment]
Will be adding to Repo soon !

**Comment by praveenscience** [comment]
Thanks, this can be closed now! 🤗
